import { Opponent } from '@/models/opponent'

const opponents: Opponent[] = [
  {
    id: 1,
    address: '0x123...123',
    ranking: 1,
    point: 456,
    squad: [
      {
        id: 1,
        name: 'Pandaslayer',
        img: '/assets/characters-demo/warrior-1.png',
        attack: 100,
        defend: 100,
        hp: 100,
        type: 'water',
        rarity: 'common',
        level: 100,
      },
      {
        id: 2,
        name: 'Pandaslayer',
        img: '/assets/characters-demo/warrior-10.png',
        attack: 100,
        defend: 100,
        hp: 100,
        type: 'fire',
        rarity: 'uncommon',
        level: 100,
      },
      {
        id: 3,
        name: 'Pandaslayer',
        img: '/assets/characters-demo/warrior-11.png',
        attack: 100,
        defend: 100,
        hp: 100,
        type: 'light',
        rarity: 'rare',
        level: 100,
      },
      {
        id: 4,
        name: 'Pandaslayer',
        img: '/assets/characters-demo/warrior-12.png',
        attack: 100,
        defend: 100,
        hp: 100,
        type: 'fire',
        rarity: 'epic',
        level: 100,
      },
      {
        id: 5,
        name: 'Pandaslayer',
        img: '/assets/characters-demo/warrior-14.png',
        attack: 100,
        defend: 100,
        hp: 100,
        type: 'water',
        rarity: 'unique',
        level: 100,
      },
    ],
    win_rate: 10,
    point_earn: 10,
  },
  {
    id: 2,
    address: '0x123...123',
    ranking: 1,
    point: 456,
    squad: [
      {
        id: 1,
        name: 'Pandaslayer',
        img: '/assets/characters-demo/warrior-1.png',
        attack: 100,
        defend: 100,
        hp: 100,
        type: 'water',
        rarity: 'common',
        level: 100,
      },
      {
        id: 2,
        name: 'Pandaslayer',
        img: '/assets/characters-demo/warrior-10.png',
        attack: 100,
        defend: 100,
        hp: 100,
        type: 'fire',
        rarity: 'uncommon',
        level: 100,
      },
      {
        id: 3,
        name: 'Pandaslayer',
        img: '/assets/characters-demo/warrior-11.png',
        attack: 100,
        defend: 100,
        hp: 100,
        type: 'light',
        rarity: 'rare',
        level: 100,
      },
      {
        id: 4,
        name: 'Pandaslayer',
        img: '/assets/characters-demo/warrior-12.png',
        attack: 100,
        defend: 100,
        hp: 100,
        type: 'fire',
        rarity: 'epic',
        level: 100,
      },
      {
        id: 5,
        name: 'Pandaslayer',
        img: '/assets/characters-demo/warrior-14.png',
        attack: 100,
        defend: 100,
        hp: 100,
        type: 'water',
        rarity: 'unique',
        level: 100,
      },
    ],
    win_rate: 10,
    point_earn: 10,
  },
  {
    id: 3,
    address: '0x123...123',
    ranking: 1,
    point: 456,
    squad: [
      {
        id: 1,
        name: 'Pandaslayer',
        img: '/assets/characters-demo/warrior-1.png',
        attack: 100,
        defend: 100,
        hp: 100,
        type: 'water',
        rarity: 'common',
        level: 100,
      },
      {
        id: 3,
        name: 'Pandaslayer',
        img: '/assets/characters-demo/warrior-11.png',
        attack: 100,
        defend: 100,
        hp: 100,
        type: 'light',
        rarity: 'rare',
        level: 100,
      },
      {
        id: 4,
        name: 'Pandaslayer',
        img: '/assets/characters-demo/warrior-12.png',
        attack: 100,
        defend: 100,
        hp: 100,
        type: 'fire',
        rarity: 'epic',
        level: 100,
      },
      {
        id: 5,
        name: 'Pandaslayer',
        img: '/assets/characters-demo/warrior-14.png',
        attack: 100,
        defend: 100,
        hp: 100,
        type: 'water',
        rarity: 'unique',
        level: 100,
      },
    ],
    win_rate: 10,
    point_earn: 10,
  },
  {
    id: 4,
    address: '0x123...123',
    ranking: 1,
    point: 456,
    squad: [
      {
        id: 1,
        name: 'Pandaslayer',
        img: '/assets/characters-demo/warrior-1.png',
        attack: 100,
        defend: 100,
        hp: 100,
        type: 'water',
        rarity: 'common',
        level: 100,
      },
      {
        id: 3,
        name: 'Pandaslayer',
        img: '/assets/characters-demo/warrior-11.png',
        attack: 100,
        defend: 100,
        hp: 100,
        type: 'light',
        rarity: 'rare',
        level: 100,
      },
      {
        id: 4,
        name: 'Pandaslayer',
        img: '/assets/characters-demo/warrior-12.png',
        attack: 100,
        defend: 100,
        hp: 100,
        type: 'fire',
        rarity: 'epic',
        level: 100,
      },
      {
        id: 5,
        name: 'Pandaslayer',
        img: '/assets/characters-demo/warrior-14.png',
        attack: 100,
        defend: 100,
        hp: 100,
        type: 'water',
        rarity: 'unique',
        level: 100,
      },
    ],
    win_rate: 10,
    point_earn: 10,
  },
  {
    id: 5,
    address: '0x123...123',
    ranking: 1,
    point: 456,
    squad: [
      {
        id: 1,
        name: 'Pandaslayer',
        img: '/assets/characters-demo/warrior-1.png',
        attack: 100,
        defend: 100,
        hp: 100,
        type: 'water',
        rarity: 'common',
        level: 100,
      },
      {
        id: 3,
        name: 'Pandaslayer',
        img: '/assets/characters-demo/warrior-11.png',
        attack: 100,
        defend: 100,
        hp: 100,
        type: 'light',
        rarity: 'rare',
        level: 100,
      },
      {
        id: 4,
        name: 'Pandaslayer',
        img: '/assets/characters-demo/warrior-12.png',
        attack: 100,
        defend: 100,
        hp: 100,
        type: 'fire',
        rarity: 'epic',
        level: 100,
      },
      {
        id: 5,
        name: 'Pandaslayer',
        img: '/assets/characters-demo/warrior-14.png',
        attack: 100,
        defend: 100,
        hp: 100,
        type: 'water',
        rarity: 'unique',
        level: 100,
      },
    ],
    win_rate: 10,
    point_earn: 10,
  },
]

export function GetOpponents() {
  return opponents
}



